version: "3.8"

services:
  portfolio:
    image: ghcr.io/jrimit/3dportfolio:latest
    container_name: portfolio-3d
    restart: always
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
